{
 "title": "Auth Service Monitoring",
 "tags": [
  "auth",
  "metrics"
 ],
 "panels": [
  {
   "title": "Successful Logins",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(auth_login_success_total[1m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Failed Logins",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(auth_login_failed_total[1m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Emails Sent",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(auth_email_sent_total[1m]))",
     "legendFormat": "emails"
    }
   ]
  },
  {
   "title": "JWT Tokens Generated",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(auth_jwt_generated_total[1m]))",
     "legendFormat": "JWT"
    }
   ]
  },
  {
   "title": "HTTP Requests Latency",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 14, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 6, "y": 14, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "RAM %"
    }
   ]
  }
 ]
}